## PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors

### Creating tensors

## ประเภทของ Tensor
https://www.kdnuggets.com/wp-content/uploads/scalar-vector-matrix-tensor.jpg

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim #เช็คมิติ

0

In [ ]:
scalar.item() #รับ tensor กลับมาเป็นจำนวนเต็มของ Python

7

In [ ]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim #มิติเปรียบเสมือนจำนวน [] ที่กำหนด

1

In [ ]:
vector.shape #เช็ครูปร่าง เปรียบเสมือนค่าใน [] แต่ละตัวที่กำหนด

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 8]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random tensors

Why random tensors?

Random tensors มีความสำคัญเนื่องจากเป็นวิธีที่ neural networks หลายแห่งเรียนรู้ คือ พวกมัน
เริ่มต้นด้วยเทนเซอร์ที่เต็มไปด้วยตัวเลขสุ่มจากนั้นจึงปรับตัวเลขสุ่มเหล่านั้นเพื่อแสดงข้อมูลได้ดีขึ้น

`Start with random number -> look at data -> update random numbers -> look at data -> update random numbers`


In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4593, 0.7716, 0.2455, 0.2752],
        [0.5700, 0.6163, 0.3693, 0.4774],
        [0.7318, 0.7030, 0.6998, 0.0974]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype # ตรวจสอบประเภทของข้อมูล

torch.float32

## Create a range of tensosrs and tensors-like

Tensors-like ใช้สร้าง Tensor ใหม่ ซึ่งมีขนาด (shape) และประเภทข้อมูล (dtype) เหมือนกับ input ที่กำหนด

In [ ]:
# Use torch.range()
torch.range(1, 10)

<ipython-input-23-fda328158a35>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1, 10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# ใช้ torch.arange แทน torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

ค่าข้อมูลเริ่มต้นของ tensor คือ float32

https://en.wikipedia.org/wiki/Precision_(computer_science)

**Note:** Tensor datatypes is one of 3 big errors you'll run into with PyTorch & Deep Learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # ประเภทข้อมูลที่ Tensor ใช้
                               device=None, # อุปกรณ์ที่ Tensor ใช้ในการประมวณผล
                               requires_grad=False) # ติดตามการไล่ระดับสีด้วยการดำเนินการเทนเซอร์นี้หรือไม่
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors (tensor attribute)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to do get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to do get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1474, 0.6622, 0.2276, 0.0949],
        [0.4178, 0.8391, 0.6085, 0.2964],
        [0.8694, 0.2968, 0.0996, 0.4462]])

In [ ]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensof: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.1474, 0.6622, 0.2276, 0.0949],
        [0.4178, 0.8391, 0.6085, 0.2964],
        [0.8694, 0.2968, 0.0996, 0.4462]])
Datatype of tensof: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating Tensors (tensor operations)

Tensor opertions include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html



มีกฎหลักสองข้อที่ต้องปฏิบัติตามในการคูณเมทริกซ์:
`(outer, inner) @ (inner, outer)`
1. The **inner dimensions** must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions** :
* `(2, 3) @ (3, 2)` -> `(2, 2)`

สัญลักษณ์ @  ถูกใช้เป็น Matrix Multiplication Operator ซึ่งเทียบเท่ากับการใช้ฟังก์ชัน torch.matmul ใน PyTorch


In [ ]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[1.1011, 0.9546],
        [1.7609, 1.2189]])

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)


tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 871 µs, sys: 983 µs, total: 1.85 ms
Wall time: 1.77 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 91 µs, sys: 0 ns, total: 91 µs
Wall time: 95.8 µs


tensor(14)

## One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm() is the same as torch.matmul เปรียบเสมือนนามแฝงให้เขียนสั้นลง
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

## เพื่อแก้ไขปัญหา shape ของ tensor เราสามารถจัดการ shapeของ tensor ตัวใดตัวหนึ่งของเราได้โดยใช้ **transpose**


transpose จะเปลี่ยนแกนหรือขนาดของเทนเซอร์ที่กำหนด

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
#The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shape: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shape: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean
# torch.mean() function requires a tensor of float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> return index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - เปลี่ยนรูปร่างเทนเซอร์อินพุตให้เป็นรูปร่างที่กำหนด
* View - คืนมุมมองของเทนเซอร์อินพุตที่มีรูปร่างบางอย่างแต่ยังคงหน่วยความจำเดียวกันกับเทนเซอร์ดั้งเดิม
* Stacking - รวมเทนเซอร์หลาย ๆ ตัวไว้ด้านบน (vstack) หรือแบบเคียงข้างกัน (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueezing - add a `1` dimension to a target tensor
* Permute - คืนมุมมองของอินพุตที่มีมิติที่สับเปลี่ยน (swapped) ในลักษณะใดลักษณะหนึ่งๆ


In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshape = x.reshape(1, 9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

`torch.stack` ใช้สำหรับ รวม Tensor หลายตัวเข้าด้วยกัน โดยเพิ่มมิติ (dimension) ใหม่เข้ามาในตำแหน่งที่ระบุด้วยพารามิเตอร์ dim โดยที่

* [x, x, x, x] หมายถึงการรวม Tensor x จำนวน 4 ชุดเข้าไปใน Tensor ใหม่
* dim=0 เพิ่มมิติใหม่ในตำแหน่ง 0 (แถวใหม่)
* dim=1 เพิ่มมิติใหม่ในตำแหน่ง 1 (คอลัมน์ใหม่)

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tenosr: {x_reshape}")
print(f"Previous shape: {x_reshape.shape}")

#Remove extra dimensions from x_reshape
x_squeezed = x_reshape.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tenosr: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [ ]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tartget: {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

Previous tartget: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - Rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# สับเปลี่ยนเทนเซอร์ดั้งเดิมเพื่อจัดเรียง axis (or dim)
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->2, 1->0, 2->1 (original_index->new_index)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


`torch.rand(size=(224, 224, 3))`

size=(224, 224, 3) คือ
*  224 แถว ซึ่งหมายถึง 224 พิกเซลในแนวตั้ง (ความสูงของภาพ)
* 224 คอลัมน์ ซึ่งหมายถึง 224 พิกเซลในแนวนอน (ความกว้างของภาพ)
* 3 ช่อง (Depth) ซึ่งหมายถึงข้อมูลสำหรับแต่ละช่องสี (เช่น RGB)

ซึ่งเป็นขนาดที่กำหนดต่อหนึ่งภาพ โดยแต่ละพิกเซลของภาพจะมีค่า 3 ช่องสี ได้แก่ Red(R), Green(G), Blue(B) ตามลำดับ

Ex.

[

    [[R, G, B], [R, G, B], ..., [R, G, B]],  # แถวที่ 1
    [[R, G, B], [R, G, B], ..., [R, G, B]],  # แถวที่ 2
    ...
    [[R, G, B], [R, G, B], ..., [R, G, B]]   # แถวที่ 224
]



In [ ]:
x_original

tensor([[[0.8238, 0.2323, 0.3870],
         [0.2134, 0.4911, 0.0309],
         [0.0072, 0.4590, 0.4074],
         ...,
         [0.1337, 0.1502, 0.6954],
         [0.1356, 0.3250, 0.8109],
         [0.0719, 0.7651, 0.6593]],

        [[0.8434, 0.5059, 0.6323],
         [0.7908, 0.1031, 0.9537],
         [0.3005, 0.4754, 0.1772],
         ...,
         [0.3499, 0.4029, 0.9522],
         [0.7744, 0.6720, 0.1321],
         [0.0440, 0.1090, 0.5117]],

        [[0.0892, 0.4708, 0.8362],
         [0.9198, 0.3736, 0.9221],
         [0.6918, 0.7599, 0.7706],
         ...,
         [0.0439, 0.3046, 0.9575],
         [0.0468, 0.4173, 0.4246],
         [0.0755, 0.9121, 0.8941]],

        ...,

        [[0.9964, 0.6411, 0.5347],
         [0.5858, 0.1665, 0.0862],
         [0.5316, 0.4277, 0.3519],
         ...,
         [0.7426, 0.4397, 0.1998],
         [0.7851, 0.0195, 0.2184],
         [0.5309, 0.1258, 0.7574]],

        [[0.8874, 0.3226, 0.8632],
         [0.9054, 0.4390, 0.4196],
         [0.

In [ ]:
# Row[0], Column[1]
x_original[0,1]

tensor([0.2134, 0.4911, 0.0309])

In [ ]:
# Row[223], Column[223]
x_original[223,223]

tensor([0.3605, 0.9951, 0.6847])

In [ ]:
# Row[0], Column[0], Green channel
x_original[0,0,1]

tensor(0.2323)

## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with Numpy.

In [ ]:
# Creater a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:,2,2]

tensor([9])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

`x[:, :, 2]` คือ
* : ในมิติที่ 1 (batch) => เลือกข้อมูลทั้งหมดใน batch (เนื่องจากมีแค่ 1 ชุด)
* : ในมิติที่ 2 (rows) => เลือกข้อมูลในทุกแถว (เนื่องจากมี 3 แถว (index 0-2))
* 2 ในมิติที่ 3 (columns) => เลือกคอลัมน์ที่ 2 (index เริ่มต้นที่ 0)

## PyTorch tensors & NumPy
Numpy เป็นไลบรารีการคำนวณเชิงตัวเลขทางวิทยาศาสตร์ที่ได้รับความนิยมในภาษา Python และเพราะเหตุนี้ PyTorch จึงมีฟังก์ชันการทำงานที่สามารถโต้ตอบกับมันได้

* Numpy > PyTorch tensor -> `torch.from_numpy(ชื่อตัวแปรที่เก็บข้อมูล numpy)`
* PyTorch > Numpy -> `ชื่อตัวแปรที่เก็บข้อมูลTensor.numpy()`

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

* หากสร้าง arange() จาก numpy จะมีค่าเริ่มต้นเป็น float64
* หากสร้าง arange() จาก pytorch จะมีค่าเริ่มต้นเป็น float32

`หากเปลี่ยนจาก numpy เป็น pytorch tensor ประเภทข้อมูลจะยังอิงตาม numpy เป็น float 64` หากอยากเปลี่ยนเป็น float32 ต้องใช้ `.type(torch.float32)` กำกับด้วย

Ex.

tensor = torch.from_numpy(array).type(torch.float32)

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# Change the value of array, what will this do to "tensor"
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to "numpy_tensor"
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## ความสมารถในการทำซ้ำ -> Reproducibility (trying to take random out of random)

How a neural network learns:

`start with random numbers -> tensor operation -> update random numbers to try and make them better representations of the data -> again -> again ...`

เพื่อลดความสุ่มในโครงข่ายประสาทเทียม PyTorch จึงมีแนวคิดเกี่ยวกับ **random seed**

โดยพื้นฐานแล้วสิ่งที่เมล็ดสุ่มทำคือ "flavour" ของการสุ่ม

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print("---------------")
print(random_tensor_B)
print("---------------")
print(random_tensor_A == random_tensor_B)

tensor([[0.7883, 0.0261, 0.1480, 0.3706],
        [0.8773, 0.6864, 0.7774, 0.0964],
        [0.1817, 0.6572, 0.5882, 0.3677]])
---------------
tensor([[0.9600, 0.1552, 0.3561, 0.7394],
        [0.7222, 0.1288, 0.9614, 0.0651],
        [0.8936, 0.7403, 0.2686, 0.5975]])
---------------
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand (3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print("---------------")
print(random_tensor_D)
print("---------------")
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
---------------
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
---------------
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


`torch.manual_seed()` ใน PyTorch ใช้สำหรับการ กำหนดค่าเริ่มต้นของตัวสร้างตัวเลขสุ่ม (random number generator) เพื่อให้ผลลัพธ์จากการสุ่มใน PyTorch เดิมทุกครั้งที่รันโค้ด (ตราบใดที่ seed เหมือนกัน)

## Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)


In [ ]:
# check GPU
!nvidia-smi

Sat Dec 28 07:34:09 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:

https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

##Putting tensor (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

ในการแก้ไขปัญหา tensor บน GPU กับ Numpy เราต้องตั้งค่า tensor ให้อยู่บน CPU เนื่องจาก Numpy ใช้งานได้กับ CPU เท่านั้น

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')